In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
from gl_functions import *
from spot_functions import *
from constants import timeout_sec
from scipy.spatial.transform import Rotation as sciRot

In [2]:
#### CONSTANTS ####
look_at_locs = np.array([[1.1, 0, -0.5],[0, 1.1, -0.5]])

obj_pos_body = geometry_pb2.Vec3(x = 0.8, y = 0, z = -0.5)

arm_pos_bounds  = {'x': {'lower':  0.6, 'upper': 0.9},
                   'y': {'lower': -0.4, 'upper': 0.4},
                   'z': {'lower': -0.1, 'upper': 0.8}}

drop_rots = np.array([
    [1,0,0],
    [-1,0,0],
    [1,0,1],
    [-1,0,1],
    [1,0,-1],
    [-1,0,-1],
    [0,1,0],
    [0,1,1],
    [0,1,2],
    [0,1,3]
])

In [3]:
sdk, robot, id_client, \
robot_state_client, command_client, \
image_client, graph_nav_client, \
world_object_client, manipulation_api_client = init_robot('192.168.50.3')

In [4]:
lease_client, lease, lease_keep_alive = get_lease(robot)

In [5]:
# Initialize Groundlight API

GROUNDLIGHT_API_TOKEN = 'api_2Au8NPiTMbSLQ73Vjr2eMhX2qUh_pt4EEKhtDNgnjN3dUAr89YANDcYsmBkJZV'
gl = Groundlight(api_token=GROUNDLIGHT_API_TOKEN)
detectors = gl.list_detectors()
eraser_det = detectors.results[0]

In [6]:
rubiks_det = detectors.results[4]

In [7]:
get_batt_info(robot_state_client)

Battery at: 100.0 %. Robot has 5627 seconds left


(100.0, 5627)

In [8]:
success = power_on(robot)

In [9]:
bdcrc.blocking_selfright(command_client, timeout_sec = 20)

In [10]:
bdcrc.blocking_stand(command_client, timeout_sec = timeout_sec)

In [319]:
move_robot_relative(command_client, robot, 0, 0, 0)

In [475]:
# cmd = RobotCommandBuilder.battery_change_pose_command()
# cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)

In [69]:
# def gripper_open_to_zero_force(command_client, 
#                                robot_state_client, 
#                                force_threshold_newtons = 1):
#     for gripper_pos in np.arange(0,1, 0.1):
#         robot_state = robot_state_client.get_robot_state()
#         gripper_load_newtons = robot_state.kinematic_state.joint_states[-1].load.value

#         print(np.round(gripper_pos,2), np.round(gripper_load_newtons,2))
        
#         if np.abs(gripper_load_newtons) < force_threshold_newtons:
#             break

#         cmd = RobotCommandBuilder.claw_gripper_open_fraction_command(gripper_pos)
#         cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)
        
#         time.sleep(1)
        
#     cmd = RobotCommandBuilder.claw_gripper_open_fraction_command(gripper_pos + 0.05)
#     cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)
#     return {'angle': gripper_pos, 'load' : gripper_load_newtons}
#         #bdcrc.block_until_arm_arrives(command_client, cmd_id, timeout_sec = time.time() + timeout_sec)

In [52]:
# def random_obj_drop(command_client, robot_state_client = None):
#     random_look_dir = np.array([((np.random.rand() * 2) - 1) * 2, 
#                  (((np.random.rand()) * 2) - 1) * 3, 
#                  np.random.rand() * (-2)  ])

# #    print(random_look_dir)
#     move_to_and_look_at(command_client, [0.8,0,-0.45],random_look_dir, True)
    
#     time.sleep(0.5)

#     if robot_state_client is None:
#         cmd = RobotCommandBuilder.claw_gripper_open_fraction_command(1.0)
#         cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)
#     else:
#         gripper_open_to_zero_force(command_client, robot_state_client)
#         time.sleep(0.5)
#         move_to_and_look_at(command_client, [0.8,0,-0.3],random_look_dir + np.array([0.8,0,-2]), True)

#     time.sleep(1)
    
#     move_to_and_look_at(command_client, [0.8,0,-0.2],random_look_dir + np.array([0,0,-0.3]), True)

#     cmd = RobotCommandBuilder.arm_stow_command()
#     cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+5)
#     bdcrc.block_until_arm_arrives(command_client, cmd_id, timeout_sec = time.time() + 3.0)
    
#     cmd = RobotCommandBuilder.claw_gripper_open_fraction_command(1.0)
#     cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)

In [110]:
def gripper_slow_open(command_client):
    
    gripper_angles = np.linspace(0, 1, 1000)
    
    for gripper_angle in gripper_angles:
        cmd = RobotCommandBuilder.claw_gripper_open_fraction_command(gripper_angle)
        cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)
        time.sleep(1/gripper_angles.shape[0])

In [111]:
gripper_slow_open(command_client)

In [82]:
np.linspace(0, np.pi/2, 100)

array([0.        , 0.01586663, 0.03173326, 0.04759989, 0.06346652,
       0.07933315, 0.09519978, 0.11106641, 0.12693304, 0.14279967,
       0.1586663 , 0.17453293, 0.19039955, 0.20626618, 0.22213281,
       0.23799944, 0.25386607, 0.2697327 , 0.28559933, 0.30146596,
       0.31733259, 0.33319922, 0.34906585, 0.36493248, 0.38079911,
       0.39666574, 0.41253237, 0.428399  , 0.44426563, 0.46013226,
       0.47599889, 0.49186552, 0.50773215, 0.52359878, 0.53946541,
       0.55533203, 0.57119866, 0.58706529, 0.60293192, 0.61879855,
       0.63466518, 0.65053181, 0.66639844, 0.68226507, 0.6981317 ,
       0.71399833, 0.72986496, 0.74573159, 0.76159822, 0.77746485,
       0.79333148, 0.80919811, 0.82506474, 0.84093137, 0.856798  ,
       0.87266463, 0.88853126, 0.90439789, 0.92026451, 0.93613114,
       0.95199777, 0.9678644 , 0.98373103, 0.99959766, 1.01546429,
       1.03133092, 1.04719755, 1.06306418, 1.07893081, 1.09479744,
       1.11066407, 1.1265307 , 1.14239733, 1.15826396, 1.17413

In [ ]:
def arm_move_to_pose(command_client, )
    

In [ ]:
def random_rot_drop(command_client, robot_state_client = None):
    drop_rot_ind = np.random.randint(drop_rots.shape[0])
    drop_rot = drop_rots[drop_rot_ind, :]
    

In [15]:
move_to_and_look_at(command_client, np.array([0.8,0,-0.45]), np.array([0.8,0,-2]))

In [20]:
move_to_and_look_at(command_client, np.array([0.8,0,-0.3]), np.array([2.8,0,-0.45]))

In [168]:
rot_quat.to_matrix()

array([[-2.22044605e-16, -2.46519033e-32, -1.00000000e+00],
       [ 1.22464680e-16, -1.00000000e+00,  0.00000000e+00],
       [-1.00000000e+00, -1.22464680e-16,  2.22044605e-16]])

In [119]:
override_response = stowable_override(manipulation_api_client)

In [120]:
cmd = RobotCommandBuilder.arm_stow_command()
cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)
bdcrc.block_until_arm_arrives(command_client, cmd_id, timeout_sec = time.time() + 3.0)

False

In [114]:
gripper_open(command_client)

In [118]:
gripper_close(command_client)

In [121]:
for drop_rot in drop_rots:
    print(drop_rot)

    rotObj = sciRot.from_euler('xyz',np.pi/2*drop_rot)
    rot_mtx = rotObj.as_matrix()
    rot_quat = bosdyn.client.math_helpers.Quat.from_matrix(rot_mtx)
    drop_pose_body_frame_proto = geometry_pb2.SE3Pose(
        position = geometry_pb2.Vec3(x = 0.8, y = 0, z = -0.3),  
        rotation = rot_quat.to_proto())
    drop_pose_body_frame_se3 = bosdyn.client.math_helpers.SE3Pose.from_proto(drop_pose_body_frame_proto)
    arm_cmd = RobotCommandBuilder.arm_pose_command(x = drop_pose_body_frame_se3.x,
                                               y = drop_pose_body_frame_se3.y,
                                               z = drop_pose_body_frame_se3.z,
                                               qw = drop_pose_body_frame_se3.rotation.w,
                                               qx = drop_pose_body_frame_se3.rotation.x,
                                               qy = drop_pose_body_frame_se3.rotation.y,
                                               qz = drop_pose_body_frame_se3.rotation.z,
                                               frame_name = 'body')

    body_cmd = RobotCommandBuilder.synchro_stand_command(body_height = -0.3)
    cmd = RobotCommandBuilder.build_synchro_command(arm_cmd, body_cmd)
    cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)
    bdcrc.block_until_arm_arrives(command_client, cmd_id, timeout_sec = time.time() + 3.0)

    time.sleep(0.5)
    
    gripper_slow_open(command_client)
    
    time.sleep(0.5)

    gripper_close(command_client)

    time.sleep(1)

    success = blocking_stow(command_client, timeout_sec = 3)

    override_response = stowable_override(manipulation_api_client)

    time.sleep(2)

[1 0 0]
[-1  0  0]
[1 0 1]
[-1  0  1]
[ 1  0 -1]


bosdyn.api.RetainLeaseResponse (LeaseUseError): 
    (resuming check-in)


[-1  0 -1]
[0 1 0]
[0 1 1]
[0 1 2]


KeyboardInterrupt: 

In [23]:
gripper_stats

{'angle': 0.0, 'load': 0.032243531197309494}

In [45]:
body_cmd = RobotCommandBuilder.synchro_stand_command(body_height = -0.2)
cmd_id = command_client.robot_command(body_cmd, end_time_secs = time.time()+timeout_sec)

In [200]:
random_obj_drop(command_client, robot_state_client)

FINAL POS, LOAD 0.3 0.051263704895973206


In [15]:
# random_obj_drop(command_client)

[ 0.19525402  1.2911362  -1.20552675]


In [206]:
cmd = RobotCommandBuilder.claw_gripper_open_fraction_command(1.0)
cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)

In [202]:
cmd = RobotCommandBuilder.claw_gripper_open_fraction_command(0.0)
cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)

In [61]:
def rand_imgs_thru_det(command_client, image_client, gl, det):
    for j in range(len(look_at_locs)):
        look_at = look_at_locs[j]
        for i in range(3):
            #Move Arm to random position
            x_pos_rand = np.random.uniform(arm_pos_bounds['x']['lower'],arm_pos_bounds['x']['upper'])
            y_pos_rand = np.random.uniform(arm_pos_bounds['y']['lower'],arm_pos_bounds['y']['upper'])
            z_pos_rand = np.random.uniform(arm_pos_bounds['z']['lower'],arm_pos_bounds['z']['upper'])

            move_to = np.array([x_pos_rand, y_pos_rand, z_pos_rand])
            move_to_and_look_at(command_client, move_to, look_at, blocking = True)

            time.sleep(0.4)

            hand_color_img, img_response = cap_hand_image(image_client, source = 'hand_color_image')
            image_query = mat_thru_det(gl, det, hand_color_img)

In [67]:
def multiAttemptGrasp(*, manipulation_api_client, command_client, graph_nav_client, obj_pos_vision):
    for i in range(5):
        print(i)
        grasp = manipulation_api_pb2.PickObject(frame_name = 'vision',
                                                object_rt_frame = obj_pos_vision)
        grasp_request = manipulation_api_pb2.ManipulationApiRequest(pick_object=grasp)
        response, success = make_grasp(grasp_request, manipulation_api_client, 
                                       command_client, graph_nav_client, verbose = True)

        curState = robot_state_client.get_robot_state()
        wrist_pos_rads = np.abs(curState.kinematic_state.joint_states[-1].position.value)

        if wrist_pos_rads < np.pi/36 or not success:
#            print(response, success)
            blocking_stow(command_client, timeout_sec = 15)
            time.sleep(3)
            continue
        else:
            return True

            
            print('GRIPPER IS CLOSED. FAILED TO GRAB CUBE')
        
    logging.warning('FAILED TO GRAB CUBE')
    return False

In [68]:
#TODO: REMOVE
det = rubiks_det

In [173]:
def drop_cap_grasp(*, manipulation_api_client, command_client, image_client, robot_state_client, gl, det):
    random_obj_drop(command_client, robot_state_client)

    #get_a_tform_b returns transformation such that a_coords = tform * b_coords
    frame_tree_snapshot = robot.get_frame_tree_snapshot()
    body_to_vision = bosdyn.client.frame_helpers.get_a_tform_b(frame_tree_snapshot, frame_a = 'vision', frame_b ='body')
    obj_pos_body_se3_proto = geometry_pb2.SE3Pose(
        position = obj_pos_body,
        rotation = bosdyn.client.math_helpers.Quat(w = 0, 
                                               x = 0, 
                                               y = -(1/2)**0.5, 
                                               z = (1/2)**0.5).to_proto())
    obj_pos_body_se3 = bosdyn.client.math_helpers.SE3Pose.from_proto(obj_pos_body_se3_proto)
    obj_pos_vision_se3 = body_to_vision * obj_pos_body_se3

    move_robot_relative(command_client, robot, -0.3, 0, 0)

    rand_imgs_thru_det(command_client, image_client, gl, rubiks_det)

    blocking_stow(command_client)

    multiAttemptGrasp(manipulation_api_client = manipulation_api_client,
                      command_client = command_client,
                      graph_nav_client = graph_nav_client,
                      obj_pos_vision = obj_pos_vision_se3.position)

    cmd = RobotCommandBuilder.arm_stow_command()
    cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)

In [174]:
drop_cap_grasp(manipulation_api_client = manipulation_api_client,
               command_client = command_client,
               image_client = image_client,
               robot_state_client = robot_state_client,
               gl = gl,
               det = det)

0
1
2
3
4


In [83]:
move_robot_relative(command_client, robot, 0, 0, np.pi/2)

In [69]:
success = multiAttemptGrasp(manipulation_api_client = manipulation_api_client, 
                            command_client = command_client, 
                            graph_nav_client = graph_nav_client, 
                            obj_pos_vision = obj_pos_vision_se3.position)

0
1
2
3
4


In [169]:
wp_loc_proto = graph_del_get_graph_loc(graph_nav_client)

In [81]:
multiAttemptGrasp(manipulation_api_client, command_client, graph_nav_client)

0


TypeError: Parameter to MergeFrom() must be instance of same class: expected bosdyn.api.Vec3 got str.

In [170]:
cmd = RobotCommandBuilder.arm_stow_command()
cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)

In [ ]:
move()

In [86]:
logging.getLogger().setLevel(logging.WARNING)

In [12]:
upload_filepath = "/home/gluser/groundlight/bdspot/spot/loopGraph"
upload_graph_and_snapshots(graph_nav_client, upload_filepath)
success = graph_localize_fiducial(command_client, graph_nav_client, robot_state_client, robot)
waypoint_list = create_waypoint_list(graph_nav_client)

In [13]:
nav_to_cmd_id = graph_nav_client.navigate_to(waypoint_list[8], cmd_duration = 15)

In [15]:
init_guess_loc_proto = graph_del_get_graph_loc(graph_nav_client)

In [26]:
move_to = np.array([0.8, 0,-0.4])
look_at = np.array([0.8, 0, -3])

In [27]:
move_to_and_look_at(command_client, move_to, look_at)

In [90]:
def get_walking_params(max_linear_vel, max_rotation_vel):
    max_vel_linear = geometry_pb2.Vec2(x=max_linear_vel, y=max_linear_vel)
    max_vel_se2 = geometry_pb2.SE2Velocity(linear=max_vel_linear,
                                           angular=max_rotation_vel)
    vel_limit = geometry_pb2.SE2VelocityLimit(max_vel=max_vel_se2)
    params = RobotCommandBuilder.mobility_params()
    params.vel_limit.CopyFrom(vel_limit)
    return params

In [130]:
params = get_walking_params(2,1.55)

In [183]:
cmd = RobotCommandBuilder.battery_change_pose_command()
cmd_id = command_client.robot_command(cmd, end_time_secs = time.time()+timeout_sec)

In [19]:
move_robot_relative(command_client, robot, 1, 0, 0)

In [17]:
move_robot_relative

<function spot_functions.move_robot_relative(command_client, robot, x_meters, y_meters, theta_rad, timeout_sec=10, blocking=True)>